apiVersion: v1
kind: Service
metadata:
  name:  "{{ .Values.appName }}-service"
  labels:
    app: {{ .Values.appName }}
spec:
  selector: 
    app: {{ .Values.appName }}
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 8080 
      protocol: TCP