version: "3"

volumes:
  postgres-soco:
    external: false

services:
  frontend:
    image: frontend-image
    environment:
      - API_URL=https://api.jouwwelzijn.nl
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - backend
  backend:
    image: backend-image
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=jouwwelzijn
      - DATABASE_PASSWORD=Abigail2001!
      - HOST=0.0.0.0
      - PORT=1337
      - PRODUCTION=true
      - URL=https://api.jouwwelzijn.nl
      - FRONTEND_URL=https://www.jouwwelzijn.nl
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    volumes:
      - postgres-soco:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: postgres
    ports:
      - 5432:5432