apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appName }}-backend-service"
spec:
  selector:
    connection-1: backend
  type: ClusterIP
  ports:
    - name: backend-port
      port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.targetPort }}
