apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-db
  labels:
    app: {{ .Values.appName }}-db
spec:
  replicas: {{ .Values.databaseDeployment.replicaCount }}
  selector:
    matchLabels:
      io.kompose.service: {{ .Values.appName }}-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}-db
    spec:
      containers:
      #TODO: look into if this good way to specify env vars
        - env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password123
            - name: POSTGRES_USER
              value: postgres
          image: postgres
          name: db
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: {{.Values.volumeName}}
      restartPolicy: Always
      volumes:
        - name: postgres-soco
          persistentVolumeClaim:
            claimName: postgres-soco
