apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-backend-service
spec:
  type: ClusterIP
  ports:
    - name: backend-port
      port: 8080
      targetPort: 8080
  selector:
    app : {{ .Values.appName }}-backend
