apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.appName }}-backend-deployment"
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      connection-0: db
      connection-1: backend
  template:
    metadata:
      labels:
        connection-0: db
        connection-1: backend
    spec:
      containers:
        - name: backend-container
          image: {{ .Values.backend.image }}
          env:
            #TODO:should find a way to assign this dynamic
            - name: DATABASE_HOST
              value: "{{ .Values.appName }}-db-service"
            - name: DATABASE_NAME
              value: {{ .Values.db.name }}
            - name: DATABASE_PASSWORD
              value: {{ .Values.db.password }}
            - name: DATABASE_PORT
              value: "{{ .Values.db.port }}"
            - name: DATABASE_USERNAME
              value: {{ .Values.db.user }}
      restartPolicy: Always
