apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appName }}-backend-service"
  annotations: 
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "http-hc-config"}'
spec:
  selector:
    connection-1: backend
  type: NodePort
  ports:
    - name: backend-port
      port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.targetPort }}
