apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-backend
  labels:
    app: {{ .Values.appName }}-backend
spec:
  replicas: {{.Values.backendDeplyoment.replicaCount}}
  # TODO: Investigate what this does
  # selector:
  #   matchLabels:
  #     io.kompose.service: backend
  # TODO: Also investigate what this does
  template:
    metadata:
      labels:
        io.kompose.service: backend
    spec:
      containers:
        #TODO: Look into env files
        - env:
            - name: DATABASE_CLIENT
              value: {{ .Values.databaseClient }}
            #should find a way to assign this dynamic
            - name: DATABASE_HOST
              value: db
            - name: DATABASE_NAME
              value: {{ .Values.databaseName }}
            - name: DATABASE_PASSWORD
              value: {{.Values.databasePassword}}
            - name: DATABASE_PORT
              value: {{.Values.databasePort}}
            - name: DATABASE_USERNAME
              value: {{.Values.databaseUsername}}
            - name: FRONTEND_URL
              value: {{.Values.frontendUrl}}
            - name: URL
              value: {{.Values.backendUrl}}
          image: backend-image
          name: backend
          ports:
            - containerPort: {{.Values.backendDeplyoment.containerPort}}
          resources: {}
      restartPolicy: Always
status: {}
