apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.appName }}-db-deployment"
  labels:
    app.kubernetes.io/name: "{{ .Values.appName }}-db"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Values.appName }}-db"
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ .Values.appName }}-db"
    spec:
      containers:
      - name: db-container
        image: postgres:{{ .Values.db.pgVersion }}
        imagePullPolicy: "IfNotPresent"
        ports:
          - containerPort: {{ .Values.db.port }}
        #TODO: look into if this good way to specify env vars and look into configmaps
        env:
          - name: POSTGRES_DB
            value: {{ .Values.db.name }}
          - name: POSTGRES_PASSWORD
            value: {{ .Values.db.password }}
          - name: POSTGRES_USER
            value: {{ .Values.db.user }}
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: {{ .Values.volumeMountName }}
      restartPolicy: Always
      volumes:
        - name: {{ .Values.volumeMountName }}
          persistentVolumeClaim:
            claimName: {{ .Values.volumeClaimName }}
