apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volumeClaimName }}
  labels:
    app: {{ .Values.volumeClaimName }}
spec:
  storageClassName: standard
  volumeName: {{ .Values.volumeName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volumeSize }}
