apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appName }}-db-service"
  selector:
    app.kubernetes.io/name: {{ .Values.appName }}-db
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.appName }}-db
  type: NodePort
  ports:
    - name: db-port
      port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}
  selector:
    app.kubernetes.io/name: {{ .Values.appName }}-db
