apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-db-service
  labels:
    app: {{ .Values.appName }}-db
spec:
  type: NodePort
  ports:
      port: 5432
  selector:
    app: {{ .Values.appName }}-db

