apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appName }}-db-service"
spec:
  selector:
    connection-0: db 
  type: ClusterIP
  ports:
  - protocol: TCP
    port: {{ .Values.db.port }}
    targetPort: {{ .Values.db.port }}