apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.appName }}-frontend-deployment"
  labels:
    app: "{{ .Values.appName }}-frontend"
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: "{{ .Values.appName }}-frontend"
  template:
    metadata:
      labels:
        app: "{{ .Values.appName }}-frontend"
    spec:
      containers:
        - name: frontend-container
          image: {{ .Values.frontend.image }}
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
      restartPolicy: Always
