apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appName }}-frontend-service"
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort : 3000
