apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.appName }}-frontend-deployment"
  labels:
    app: "{{ .Values.appName }}-frontend"
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: frontend
      connection-1: backend
      webapp: gke-lb-frontend
  template:
    metadata:
      labels:
        webapp: gke-lb-frontend
        app: frontend
        connection-1: backend
    spec:
      containers:
        - name: frontend-container
          image: {{ .Values.frontend.image }}
          imagePullPolicy: Always
          env:
            - name: REACT_APP_BACKEND_URL
              value: "http://34.91.87.4:81"
          ports:
            - containerPort :  3000
          volumeMounts:
            - mountPath: "/app/cert"
              name: secret-tls
              readOnly: true      
      restartPolicy: Always
      volumes:
        - name: secret-tls
          secret: 
            secretName: secret-tls
