apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appName }}-frontend-service"
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.appName }}-frontend
  ports:
    - protocol: TCP
      containerPort: {{ .Values.frontend.containerPort }}
      port: {{ .Values.frontend.targetPort }}
  selector:
    app: "{{ .Values.appName }}-frontend"
status:
  loadBalancer: {}
