apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-frontend-service
spec:
  ports:
  - protocol : TCP
    port: {{.values.frontendPort}}
    targetPort: {{.values.frontendTargetPort}}
  selector:
    app : {{ .Values.appName }}-frontend
status:
  loadBalancer: {}
