apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appName }}-frontend-service"
spec:
  ports:
    - protocol: TCP
      containerPort: {{ .Values.frontend.containerPort }}
      targetPort: {{ .Values.frontend.targetPort }}
  selector:
    app: "{{ .Values.appName }}-frontend"
status:
  loadBalancer: {}
