apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.appName }}-frontend-deployment"
  labels:
    app: "{{ .Values.appName }}-frontend"
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        version: "2.0"
    spec:
      containers:
        - name: frontend-container
          image: {{ .Values.frontend.image }}
          imagePullPolicy: Always
          env:
            - name: REACT_APP_BACKEND_URL
              value: {{ .Values.backendUrl }}
          ports:
            - containerPort :  3000    
      restartPolicy: Always
