apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.appName }}-frontend-deployment"
  labels:
    app: "{{ .Values.appName }}-frontend"
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: frontend
      connection-1: backend
  template:
    metadata:
      labels:
        app: frontend
        connection-1: backend
    spec:
      containers:
        - name: frontend-container
          image: {{ .Values.frontend.image }}
          env:
            - name: REACT_APP_BACKEND_URL
              value: "http://{{ .Values.appName }}-backend-service:8080"
          ports:
            - containerPort :  3000
      restartPolicy: Always
