apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: main
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  type: pd-standard
  fstype: ext4
  replication-type: none