kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Values.volumeName }}
  labels:
    type: local
    app: "{{.Values.appName}}-db"
spec:
  storageClassName: standard
  capacity:
    storage: {{ .Values.volumeSize }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/usr/share/postgres/data"
