apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    # This tells Google Cloud to create an External Load Balancer to realize this Ingress
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: 34.96.121.17
    # This enables HTTP connections from Internet clients
    kubernetes.io/ingress.allow-http: "false"
    cert-manager.io/issuer: letsencrypt-staging
spec:
  tls:
    - secretName: web-ssl
      hosts:
        - jouwwelzijn.nl
  # defaultBackend:
  #   service:
  #     name: "{{ .Values.appName }}-frontend-service"
  #     port:
  #       number: 80
  rules:
    - http:
        paths:
        - path: /*
          pathType: ImplementationSpecific
          backend:
            service:
              name: "{{ .Values.appName }}-frontend-service"
              port:
                number: 80
