# Default values for webapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
appName: webapp


# Volume
volumeMountName: webapp-pv-mount
volumeClaimName: webapp-pv-claim
volumeName: webapp-pv-volume
volumeSize: 1Gi


# Database
db:
  pgVersion: latest
  port: 5432
  user: postgres
  password: password123
  name: postgres


# Backend
backend:
  image: webapp/backend:latest
  replicaCount: 1
  containerPort: 8080
  targetPort: 3000
  port : 1234

# Frontend
frontend:
  image: webapp/frontend:latest
  replicaCount: 1
  containerPort: 3000
  targetPort: 80


service:
  type: ClusterIP
  port: 80
  url : "test.test.com" 
