# Default values for webapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
appName: webapp

# Volume
volumeMountName: webapp-pv-mount
volumeClaimName: webapp-pv-claim
volumeName: webapp-pv-volume
volumeSize: 10

# Database
db:
  pgVersion: latest
  port: 5432
  user: postgres
  password: password123
  name: postgres

# Backend
backend:
  # image is also publicly available on docker hub at: joshjess/backend:latest
  image: europe-west4-docker.pkg.dev/united-course-375913/soco/backend:latest
  replicaCount: 1
  port: 8080

# Frontend
frontend:
  # image is also publicly available on docker hub at: joshjess/frontend:latest
  image: europe-west4-docker.pkg.dev/united-course-375913/soco/frontend:latest
  replicaCount: 1
  port: 80
  containerPort: 80
  backendUrl: api.jouwwelzijn.nl

service:
  type: ClusterIP
  port: 80
  url: "test.test.com"
